/* !! This file was automatically generated by NEWVERS !! */

/* for logfiles, etc. */
char MPP_Version[] =
    "2.7.2 (24-06-1997)";

/* interactive 'hello' string to identify us to the user */
char MPP_Hello[] = 
    "This is MPP Version 2.7.2 (24-06-1997)";

/* a GNU --version output */
char MPP_GNUVersion[] =
    "MPP Version 2.7.2";

/* a UNIX what(1) id string */
char MPP_WhatID[] =
    "@(#)MPP Version 2.7.2 (24-06-1997)";

/* a RCS ident(1) id string */
char MPP_RCSIdentID[] =
    "$Id: MPP 2.7.2 24-06-1997 $";

/* a WWW id string */
char MPP_WebID[] =
    "MPP/2.7.2";

/* a plain id string */
char MPP_PlainID[] =
    "2.7.2";

