/* !! This file was automatically generated by NEWVERS !! */

/* for logfiles, etc. */
char BIM_Version[] =
    "1.0.0 (19-06-1997)";

/* interactive 'hello' string to identify us to the user */
char BIM_Hello[] = 
    "This is BIM Version 1.0.0 (19-06-1997)";

/* a GNU --version output */
char BIM_GNUVersion[] =
    "BIM Version 1.0.0";

/* a UNIX what(1) id string */
char BIM_WhatID[] =
    "@(#)BIM Version 1.0.0 (19-06-1997)";

/* a RCS ident(1) id string */
char BIM_RCSIdentID[] =
    "$Id: BIM 1.0.0 19-06-1997 $";

/* a WWW id string */
char BIM_WebID[] =
    "BIM/1.0.0";

/* a plain id string */
char BIM_PlainID[] =
    "1.0.0";

