/* !! This file was automatically generated by NEWVERS !! */

/* for logfiles, etc. */
char MAX_Version[] =
    "7.4.1 (08-04-1998)";

/* interactive 'hello' string to identify us to the user */
char MAX_Hello[] = 
    "This is MAX Version 7.4.1 (08-04-1998)";

/* a GNU --version output */
char MAX_GNUVersion[] =
    "MAX Version 7.4.1";

/* a UNIX what(1) id string */
char MAX_WhatID[] =
    "@(#)MAX Version 7.4.1 (08-04-1998)";

/* a RCS ident(1) id string */
char MAX_RCSIdentID[] =
    "$Id: MAX 7.4.1 08-04-1998 $";

/* a WWW id string */
char MAX_WebID[] =
    "MAX/7.4.1";

/* a plain id string */
char MAX_PlainID[] =
    "7.4.1";

